# This file configures the analyzer to use the lint rule set from `package:flutter_lints`

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 额外的 lint 规则
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_print: false  # 允许使用 print 用于日志
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: false
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # 将某些警告视为错误
    invalid_annotation_target: ignore
